version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "01:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "imtoopunkforyou"
    assignees:
      - "imtoopunkforyou"
ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
